# Generated by Django 3.1.3 on 2020-12-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sqldialect', '0001_initial'),
        ('databaseconnection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('pipeline_sql', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VirtualDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseconnection.integration')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('virtual_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.virtualdatabase')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('virtual_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.virtualschema')),
            ],
        ),
        migrations.CreateModel(
            name='ViratualColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('actual_name', models.CharField(max_length=500)),
                ('length', models.CharField(max_length=20)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqldialect.datatypemapping')),
                ('virtual_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.virtualtable')),
            ],
        ),
    ]
