# Generated by Django 3.1.3 on 2021-01-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViratualColumn',
            new_name='VirtualColumn',
        ),
    ]
