# Generated by Django 3.1.3 on 2021-01-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SqlDialect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('credential', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetDatatype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqldialect.sqldialect')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDatatype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqldialect.sqldialect')),
            ],
        ),
        migrations.CreateModel(
            name='DatatypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_datatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqldialect.sourcedatatype')),
                ('target_datatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqldialect.targetdatatype')),
            ],
        ),
    ]
