# Generated by Django 3.1.3 on 2021-02-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('repetition_type', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('day_of_month', 'Day of Month'), ('month', 'Month'), ('day_of_week', 'Day of Week')], max_length=20, null=True)),
                ('repetition_value', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
