# Generated by Django 3.1.3 on 2020-12-29 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseconnection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', related_query_name='destination', to='databaseconnection.databaseconnecion'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', related_query_name='source', to='databaseconnection.databaseconnecion'),
        ),
    ]
